core:
  project_name: 'md-csc'
  dataset_root: ./dataset/
  results_path: ./results
  version: 1
  tags: continual learning, neural networks, deep learning, regularization, class incremental learning
  author: Jary Pomponi
  github_repo: https://github.com/jaryP/Cascaded-Scaling-Classifier

defaults:
  - hydra: base
  - optimizer: sgd
  - head: incremental
  - model: null
  - experiment: base
  - evaluation: default
  - override hydra/job_logging: console
  - _self_

device: cpu
trainer_name: ${method_path:${method._target_}}

# Wandb and debug stuff
wandb_prefix: null
wandb_tags: null
enable_wandb: Yes
debug_path: null
